### ISSUE TITLE
Loosening restrictions on tuple types "Array contains Val"

### ISSUE THREAD

**Issue by douglasg14b** [samchon/typia#1299]
_I have read through the docs before coming here, if I missed something important my apologies_

## Question

I need to validate a tuple type: `[Status]` where:

1. the actual array only need to _contain_ a `Status` _anywhere_ within the array regardless of it's index.
2. The array must have a length > 1
3. There can be as many or no elements before of after `Status`

Essentially `Must contain a Status, anywhere` is the validation requirement. Which sounds deceptively simple, but is turning out to be rather difficult to actually get generated.

I'm struggling to do this with `typia`:

- a `Status[]` is an arrya of only `Status`
- A `[...unknown[], Status]` is an array with `Status` as the last element
- A `[...unknown[], Status, ...unknown[]]` is an invalid type
- `[...unknown[], Status] | [Status, ...unknown[]` 
    - **Doesn't produce a correct validator**: `['stuff', 'SUCCESS']` fails validation
    - `tuplePredicators` expect the array to be of length `1` or `2` only. And only expects a `Status` at `[0]`?
- A `string[] | [Status]` is a valid type but results in `nonsensible intersection`
- A `Array<Status> & Array<unknown>`  results in `nonsensible intersection` (This wouldn't make sense for typing anyways)

How do I do this?

_I do recognize the asinine-ness of this value, but... legacy system modeling_

**Comment by douglasg14b** [comment]
Also interestingly:

```ts
// This will generate
export type InArray<TVal> =
    | [TVal]
    | [unknown, TVal]
    | [TVal, unknown];

// This will fail with: TypeError: Cannot read properties of undefined (reading 'any')
export type InArray<TVal> =
    | [TVal]
    | [unknown, TVal]
    | [TVal, unknown]
    | [TVal, unknown, unknown]
    | [unknown, TVal, unknown]
    | [unknown, unknown, TVal];
```

**Comment by samchon** [comment]
> Also interestingly:
> 
> ```ts
> // This will generate
> export type InArray<TVal> =
>     | [TVal]
>     | [unknown, TVal]
>     | [TVal, unknown];
> 
> // This will fail with: TypeError: Cannot read properties of undefined (reading 'any')
> export type InArray<TVal> =
>     | [TVal]
>     | [unknown, TVal]
>     | [TVal, unknown]
>     | [TVal, unknown, unknown]
>     | [unknown, TVal, unknown]
>     | [unknown, unknown, TVal];
> ```

I'm testing on it but error is not occured. Which value occurs the error?

https://typia.io/playground/?script=JYWwDg9gTgLgBDAnmYBDOAzKERwERIqp4DcAUGYQKZwAqAaqgDZwC8cAdgK4gBGVUclQAekWAmQ0AkhwCCUKKkRsycNXAA+cANoNmAXVXqt2rhwDWHCAHcOAGjqMmh9Zp16mDs5ZscXx9ycvCytbYJ9bfzUTb1D7R2ZwuKi3UxDfJIyE53IyAGMIDgBneGAitgkiADo8qCpUGCopIoAeGXlFRAA+AAoASnIC4ogmKiqmCABzHqMynu08Qqo8BwAmBwBmfT67Mj6gA

**Comment by samchon** [comment]
About the rest elements type in the first or middle position in the tuple, I haven't known the spec.

By the way, I may need more investigation times because it is actually not possible in the JSON schema specification.

If neccessary, I may prohibit the type due to the JSON schema reason.

**Comment by douglasg14b** [comment]
Thanks for the reply @samchon !! I really appreciate it ^_^

Here's the stacktrace/error for the above:

```
> pnpm typia generate --input ./src/validators/templates --output ./src/validators/generated --project tsconfig.json

----------------------------------------
 Typia Generate Wizard
----------------------------------------
TypeError: Cannot read properties of undefined (reading 'any')
    at Metadata.covers (/home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/schemas/metadata/Metadata.js:371:20)
    at /home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/schemas/metadata/Metadata.js:415:75
    at Array.every (<anonymous>)
    at /home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/schemas/metadata/Metadata.js:415:34
    at Array.some (<anonymous>)
    at _loop_4 (/home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/schemas/metadata/Metadata.js:411:30)
    at Metadata.covers (/home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/schemas/metadata/Metadata.js:423:35)
    at /home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/factories/internal/metadata/iterate_metadata_sort.js:146:48
    at Array.sort (<anonymous>)
    at /home/douglas/programming/[redacted]/node_modules/.pnpm/typia@6.10.4_typescript@5.6.2/node_modules/typia/lib/factories/internal/metadata/iterate_metadata_sort.js:141:29
```

**Comment by samchon** [comment]
Revisited against the typia v13 native transform (typescript-go based) — the originally reported defects are resolved there:

- **The `Metadata.covers` crash** (`Cannot read properties of undefined (reading 'any')`) on the 6-member `InArray<TVal>` tuple union no longer occurs: the union compiles and validates correctly, accepting `Status` at any of the modeled positions and rejecting arrays without one.
- **`[...unknown[], Status] | [Status, ...unknown[]]` now accepts `['stuff', 'SUCCESS']`** — the wrong tuple-predicator routing is gone.

For the actual goal — *"must contain a `Status` anywhere, length > 1"* — TypeScript itself cannot express `[...unknown[], Status, ...unknown[]]`, so no finite tuple union scales. The supported way is a custom type tag, which compiles to exactly the `some()` check you want:

```typescript
import typia, { tags } from "typia";

type ContainsStatus = string[] &
  tags.MinItems<2> &
  tags.TagBase<{
    kind: "containsStatus";
    target: "array";
    value: undefined;
    validate: '$input.some((elem) => elem === "SUCCESS" || elem === "FAILURE")';
  }>;

const validate = typia.createValidate<ContainsStatus>();
validate(["a", "SUCCESS", "b"]); // ✓
validate(["a", "b"]);            // ✗ containsStatus violated
validate(["SUCCESS"]);           // ✗ MinItems<2> violated
```

(verified working on the v13 dev build; see https://typia.io/docs/validators/tags/#customization)

Two residual defects surfaced while verifying this and are now tracked separately:

- #1932 — non-trailing rest elements (`[...unknown[], Status]` alone) still emit positionally wrong checks;
- #1933 — type tags intersected with `unknown[]`/`any[]` are silently dropped, so the recipe above needs a concrete element type for now.

Closing this one in their favor; both fixes will ship in the v13 line. Thanks for the thorough report and the reproduction cases — they aged well.
