### ISSUE TITLE
Question: build javascript, `"build": "ttsc -b"`, Error on TSON.assertEquals(): no transform has been configured. Configure the \"tsconfig.json\" ...

### ISSUE THREAD

**Issue by larahroth** [samchon/typia#376]
Hi!

I've scoured the interwebs seeking an answer to this question to no avail, so thought you may be able to help me.
- https://github.com/cevek/ttypescript#ttypescript
- https://www.typescriptlang.org/docs/handbook/compiler-options.html

There is this node16 typescript lambda that compiles to javascript before deployment. Currently the package json has the following command as build:

```
"scripts": {
    "test": "jest --watch",
    "test:ci": "jest",
    "local": "ts-node -C ttypescript src/main.ts ",
    "lint": "eslint . --ext .ts",
    "build": "ttsc -b"
  },
```

When testing the compiled code, I receive the following error:
```
> node dist/main.js
ERROR Error: Error on TSON.assertEquals(): no transform has been configured. Configure the "tsconfig.json" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)
    at halt (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/node_modules/typescript-json/lib/module.js:352:11)
    at assertEquals (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/node_modules/typescript-json/lib/module.js:118:5)
    at handler (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/dist/interactor/lambda.js:42:44)
    at Object.<anonymous> (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/dist/main.js:14:22)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47
{
  "_err": "Error on TSON.assertEquals(): no transform has been configured. Configure the \"tsconfig.json\" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)",
  "_nytTimestamp": "23-11-2022 13:13:39.766",
  "_id": "KvqHraDRFJ7yzzxk3E_mB",
  "logUrl": "",
  "_stack": "Error: Error on TSON.assertEquals(): no transform has been configured. Configure the \"tsconfig.json\" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)\n    at halt (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/node_modules/typescript-json/lib/module.js:352:11)\n    at assertEquals (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/node_modules/typescript-json/lib/module.js:118:5)\n    at handler (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/dist/interactor/lambda.js:42:44)\n    at Object.<anonymous> (/Users/lararoth/Documents/GitHub/pubtech-stx/functions/source-processor/dist/main.js:14:22)\n    at Module._compile (node:internal/modules/cjs/loader:1119:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)\n    at Module.load (node:internal/modules/cjs/loader:997:32)\n    at Module._load (node:internal/modules/cjs/loader:838:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)\n    at node:internal/main/run_main_module:18:47"
}
```

This is my `.tsconfig.json`: 
```
{
  "extends": "@tsconfig/node16/tsconfig.json",
  "compilerOptions": {
    "types": ["node"],
    "outDir": "dist",
    "resolveJsonModule": true,
    "allowJs": true,
    "strict": true,
    "plugins": [
      {
        "transform": "typescript-json/lib/transform" //https://www.npmjs.com/package/typescript-json
      }
    ]
  },
  "include": ["src/**/*"]
}
```

Unrelated, but may help someone else. Spent a while figuring this one out which is for jest in the `jest.config.js`: 
```
  globals: {
    "ts-jest": {
      tsconfig: "__tests__/tsconfig.json",
      compiler: "ttypescript",
    },
  },
```

Thank you so much in advance. Really appreciate it.

Edit:
Forgot to mention this runs great when running locally.

**Comment by samchon** [comment]
#351

TS 4.9.3 has a bug. Recommend to downgrade to 4.8.4

**Comment by sunrabbit123** [comment]
I'm also being reproduced. But typescript is ^4.7.4. What's the problem?

**Comment by sunrabbit123** [comment]
I'm sorry, 4.9.* called by ^4.7.4

**Comment by samchon** [comment]
`npx ttsc` does not work?

**Comment by larahroth** [comment]
> #351
> 
> TS 4.9.3 has a bug. Recommend to downgrade to 4.8.4

Is this a known bug? Are you able to provide a link to the issue so I can share with my team please? :D

**Comment by samchon** [comment]
@nyt-larahelenaroth https://github.com/microsoft/TypeScript/issues/51542

**Comment by larahroth** [comment]
Downgrading to `4.8.4` still did not solve the issue we're seeing :( 

Example Typescript for this: 
```
  // Check environment variables
  const envValid = equals<AWSEnvironment>(awsEnv);
  if (!envValid) {
    const { errors } = validateEquals<AWSEnvironment>(awsEnv);
    console.warn("ERROR", errors);
    await log.error(errors);
    return; // gracefully shut down lambda
  }
```

After built in js: 
```
 // Check environment variables
    const envValid = (0, typescript_json_1.equals)(awsEnv);
    if (!envValid) {
        const { errors } = (0, typescript_json_1.validateEquals)(awsEnv);
        console.warn("ERROR", errors);
        await log.error(errors);
        return; // gracefully shut down lambda
    }
```

Error:
```
...../node_modules/typescript-json/lib/module.js:352
    throw new Error("Error on TSON.".concat(name, "(): no transform has been configured. Configure the \"tsconfig.json\" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)"));
          ^

Error: Error on TSON.equals(): no transform has been configured. Configure the "tsconfig.json" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)
```

**Comment by samchon** [comment]
@nyt-larahelenaroth Check your TS version through package-lock.json again

**Comment by bradennapier** [comment]
This package does not work @samchon i get the same thing and absolutely do not have 4.9 installed....

```
❯ npx tsc --version
Version 4.7.4
```

```typescript
// ./test.ts
import TSON from 'typescript-json';
type Test = {
  test: string;
};
console.log(TSON.is<Test>({ test: 'hi' }));
```

```
npx ts-node -C ttypescript ./test.ts
```

```
Error: Error on TSON.is(): no transform has been configured. Configure the "tsconfig.json" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)
```

Of note... my `tsconfig.json` is:

```json
{
  "extends": "./src/tsconfig.base.json"
}
```

which resolves to:

```json
{
  "compilerOptions": {
...
    "paths": {
...
    },
    "plugins": [
      {
        "transform": "@ovos-media/ts-transform-paths"
      },
      {
        "transform": "typescript-json/lib/transform"
      }
    ]
  },
  "ts-node": {
    "compilerHost": true,
    "transpileOnly": true
  }
}
```

**Comment by bradennapier** [comment]
I would rather not use `ttypescript` anyway as I use `ts-patch` so just having the plugins should be enough.

it does work when compiling but it does not work when running the code using `ts-node` etc

My guess is you have a check that is not properly working because it is not seeing something in a config and not resolving the config properly.

**Comment by bradennapier** [comment]
Ok you do not support transpile only makes sense

**Comment by larahroth** [comment]
I have triple checked that I have `4.8.4` installed, and definitely do.

`package.json`: 
```
    "typescript": "^4.8.4"
```

terminal: 
```
npx tsc -v
Version 4.8.4
```

```
 node dist/main.js
....../node_modules/typescript-json/lib/module.js:352
    throw new Error("Error on TSON.".concat(name, "(): no transform has been configured. Configure the \"tsconfig.json\" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)"));
```

@bradennapier I need a solution that is possible for both compiling and running with `ts-node`.

This is being called [here](https://github.com/samchon/typescript-json/blob/bc4bc5d116a1fd76a3029fa3a91cfb8f5423bfb0/src/module.ts#L1877):
```
function halt(name: string): never {
    throw new Error(
        `Error on TSON.${name}(): no transform has been configured. Configure the "tsconfig.json" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)`,
    );
}
```

When compiled to javascript it turns out to be: 

```
exports.createObject = createObject;
function halt(name) {
    throw new Error("Error on TSON.".concat(name, "(): no transform has been configured. Configure the \"tsconfig.json\" file following the [README.md#setup](https://github.com/samchon/typescript-json#setup)"));
}
```
The equals function once compiled looks like:
```
function equals() {
    halt("equals");
}
exports.equals = equals;
(function (equals) {
    equals.is_uuid = _is_uuid_1.$is_uuid;
    equals.is_email = _is_email_1.$is_email;
    equals.is_url = _is_url_1.$is_url;
    equals.is_ipv4 = _is_ipv4_1.$is_ipv4;
    equals.is_ipv6 = _is_ipv6_1.$is_ipv6;
    equals.join = _join_1.$join;
})(equals = exports.equals || (exports.equals = {}));
```

Thanks in advance :D

**Comment by bradennapier** [comment]
You may want to indicate in documentation that you do not support transpile only as that is much faster to do when running code with `ts-node` and is often used by default by people

**Comment by samchon** [comment]
@bradennapier OK, will document at v4 update.

**Comment by samchon** [comment]
@nyt-larahelenaroth Remove the `^` symbol and reinstall the `typescript` again.

```bash
// ERASE IT AND
"typescript": "^4.8.4"

// CHANGE LIKE BELOW
"typescript": "4.8.4"
```

**Comment by DanielRosenwasser** [comment]
4.9.4 is now out FWIW

**Comment by larahroth** [comment]
4.9.4 has resolved this issue
