### ISSUE TITLE
The `generate` option does not work with a fresh project of Vite with React

### ISSUE THREAD

**Issue by TheYarin** [samchon/typia#552]
## Bug Report

I created an online demo here: https://stackblitz.com/edit/vitejs-vite-if2xwg?file=tsconfig.json

The only thing I added to the newly created project is the `src/typia-templates` folder.

Running the following command: `npx typia generate --input src/typia-templates --output src/typia-generated --project tsconfig.json`
produces the following error:
```
----------------------------------------
 Typia Generate Wizard
----------------------------------------
Error: Debug Failure. Unexpected moduleResolution: Node
    at Object.resolveModuleName (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:44046:37)
    at loader_1 (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:119377:117)
    at loadWithModeAwareCache (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:118997:46)
    at actualResolveModuleNamesWorker (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:119378:149)
    at resolveModuleNamesWorker (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:119667:26)
    at resolveModuleNamesReusingOldState (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:119765:24)
    at processImportedModules (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:121296:35)
    at findSourceFileWorker (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:121076:17)
    at findSourceFile (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:120922:26)
    at eval (file:///home/projects/vitejs-vite-if2xwg/node_modules/typescript/lib/typescript.js:120871:85)
Error: spawn node EPERM

Code: EPERM
```

Now, I did some digging and it looks like the problem is fixed when I open `tsconfig.json` and replace `"moduleResolution": "Node",` with `"moduleResolution": 2,`. Looks like typescript doesn't like receiving the normal value from `tsconfig.json`, it wants the enum representation instead.

I was able to bypass the issue by creating `typia.tsconfig.json` with the following content:

```json
{
  "extends": "./tsconfig.json",
  "compilerOptions": { "moduleResolution": 2 }
}
```

(Bypass found thanks to [this issue](https://github.com/microsoft/TypeScript/issues/23564#issuecomment-383092947) and [this issue](https://github.com/seek-oss/playroom/issues/236#issuecomment-922278417)

**Comment by kongweiying2** [comment]
I'm getting this issue too, but with Next.js + React

**Comment by kongweiying2** [comment]
@TheYarin 

How do you get this bypass working? Is it just by creating a typia.config.json?

**Comment by samchon** [comment]
Can someone summarize this issue?

As my main job is not frontend development, it is hard for me to analyze this issue

It would best if send a README PR in the Setup section.

**Comment by TheYarin** [comment]
@kongweiying2 I bypassed the issue by also passing `--project tsconfig.typia.json` to the `npx typia generate` command.
(The file name (`tsconfig.typia.json`) is arbitrary :))

**Comment by TheYarin** [comment]
@samchon If I understand correctly, the problem is that when calling typescript via its API with the `moduleResolution` compiler option, it requires a numeric (enum) value instead of the string value that is usually used in the `tsconfig.json` file. (That's just plain confusing)

To bypass the issue, I created a new tsconfig file that extends the original one with a numeric value for `moduleResolution`.
(I didn't want to modify the original `tsconfig.json` to avoid breaking anything)

**Comment by kongweiying2** [comment]
Thanks that works well!
