### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'atomics')

### ISSUE THREAD

**Issue by Danes99** [samchon/typia#704]
# Bug Report

## 📝 Summary

- **Typia Version**: 4.1.2
- **Expected behavior**: Check type
- **Actual behavior**: Crash when generating type checker function

```bash
npx ts-node src/test.ts
/Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:87
            return has_atomic("number")(new Set())(metadata) &&
                                                  ^
TypeError: Cannot read properties of null (reading 'atomics') - /Users/machine.user/Documents/projects/check-types-project/src/test.ts:25:40
    at /Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:300:22
    at /Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:306:42
    at Array.some (<anonymous>)
    at /Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:305:29
    at type (/Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:87:51)
    at parse (/Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:37:16)
    at /Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/MetadataTagFactory.ts:13:51
    at /Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/internal/metadata/emplace_metadata_object.ts:66:72
    at _loop_1 (/Users/machine.user/Documents/projects/check-types-project/node_modules/typia/src/factories/internal/metadata/emplace_metadata_object.ts:112:65)
    at /Users/machine.user/Documents/projects/check-types-project/node_modules/typia/lib/factories/internal/metadata/emplace_metadata_object.js:111:25
```

## ⏯ Playground Link

<https://typia.io/playground/?script=JYWwDg9gTgLgBAbzgSQGoEMA2wAm6bAQB2ANHAG5a74CmcAvnAGZQQhwDkMAnmMOhwDcAKGE0AHpFhxgRGDShN0AYzoBZbsjkKlqxMLhwA9ACoTBw+cNwTcAAI8wdBAEEoUdNwA8GrfMUqNAB89BY29iA0IABGChBMcL7aAaphJkYW2ADOMABccG4e3kn+usEiocJMAK5EygTEcCDosgAUAJT6hsrEOczQNMAA5kQA8tEAVjT1+ehE3HAAvF3WAPq4+RwAbAAsAJw0KtEATMd7AMw7AIznAKw0AAzRTNE76Oi3HCRhMkQ4EvkHt9rHAhtUNpwcFctsomMcAOxMAC001ueyRO3O8NuSPQ51iSNuDxoV1uAA4aMcrodlF8fsAsi56sByDR8kpMFkaMDrNEsHNVJsACRXEg3MkAOnJdJBfHq1SgbM4AAsYDAwLkjEYwJhAsqIJgcBLgDAjOdjuJzTLrOghkrjkCfjRuDQAMIG6CbaKYao0a2GIjoSKbADKMFYRCGcAA0nM-Tz6CILD0iH1KNg8A0iAAlGhZaqYPIoDAZ-CEIhLH7p6jyLyFTw+TTJMpBIKtJgDYZjSbTGDtJOGYAJVrVzPl3P5wsS-PKVRZLKdBA-FNZA00CWYCBDVocUYAaw4-YsjBonOcy96a43W5HVDHxAnBZgEoUrCgC5EhlClWabSPQA>

## 💻 Code occuring the bug

```typescript
import { IValidation, validate } from 'typia';

export interface MyInterface {
  /**
   *
   * @type {Array<MyInterface>}
   * @memberof MyInterface
   */
  list: Array<MyInterface>;
}

function main() {
  const foreignObject: any = {
    _id: '649eacb22934135e0bfb4aa5',
    index: 0,
    guid: 'd16cf27f-ec59-4375-a3be-50e158e21eac',
    isActive: false,
    balance: '$1,138.58',
    picture: 'http://placehold.it/32x32',
    age: 20,
    eyeColor: 'blue',
    name: 'Strong Kane',
  };

  const validationResult: IValidation =
    validate<Array<MyInterface>>(foreignObject);

  if (validationResult.success) {
    console.log('Ok');
  } else {
    console.log(validationResult.errors);
  }
}

main();
```

**Comment by samchon** [comment]
Upgrade to v4.1.3, then be fixed
