### ISSUE TITLE
Application issue when upgraded to 5.0.0

### ISSUE THREAD

**Issue by oo00spy00oo** [samchon/typia#795]
## Bug Report

I cannot start my NestJS application after upgrade to 5.0.0

### 📝 Summary
Write a short summary of the bug in here.

  - **Typia Version**: 5.0.0
  - **Expected behavior**:  Start normally the same way as 4.3.3
  - **Actual behavior**: 
```
er@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/TypedRouteTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/MethodTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/NodeTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/FileTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transform.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typia@5.0.0_typescript@5.2.2/node_modules/typia/lib/transform.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/utils/typescript/load-ts-transformers.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/index.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/utils/with-nx.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/lib/get-webpack-config.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/config/schema-utils.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/executor-utils.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/run.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/bin/run-executor.js
    at makeWebpackError (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/webpack@5.88.2/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/webpack@5.88.2/node_modules/webpack/lib/Compilation.js:3068:12
    at eval (eval at create (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:23:1)
    at fn (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/webpack@5.88.2/node_modules/webpack/lib/Compilation.js:481:17)
    at _next0 (eval at create (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:21:1)
    at eval (eval at create (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
    at eval (eval at create (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/webpack@5.88.2/node_modules/webpack/lib/Compilation.js:503:10
    at Hook.eval [as callAsync] (eval at create (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/tapable@2.2.1/node_modules/tapable/lib/Hook.js:18:14)
-- inner error --
Error: Cannot find module 'typia/lib/programmers/AssertStringifyProgrammer'
Require stack:
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/TypedRouteTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/MethodTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/NodeTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/FileTransformer.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transform.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typia@5.0.0_typescript@5.2.2/node_modules/typia/lib/transform.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/utils/typescript/load-ts-transformers.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/index.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/utils/with-nx.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/lib/get-webpack-config.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/config/schema-utils.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/executor-utils.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/run.js
- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/bin/run-executor.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js:19:35)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19) {
  details: 'caused by plugins in Compilation.hooks.processAssets\n' +
    "Error: Cannot find module 'typia/lib/programmers/AssertStringifyProgrammer'\n" +
    'Require stack:\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/TypedRouteTransformer.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/MethodTransformer.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/NodeTransformer.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/FileTransformer.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transform.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typia@5.0.0_typescript@5.2.2/node_modules/typia/lib/transform.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/utils/typescript/load-ts-transformers.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/index.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/utils/with-nx.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/lib/get-webpack-config.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/config/schema-utils.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/executor-utils.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/run.js\n' +
    '- /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/bin/run-executor.js\n' +
    '    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:920:27)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1141:19)\n' +
    '    at require (node:internal/modules/cjs/helpers:110:18)\n' +
    '    at Object.<anonymous> (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js:19:35)\n' +
    '    at Module._compile (node:internal/modules/cjs/loader:1254:14)\n' +
    '    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)\n' +
    '    at Module.load (node:internal/modules/cjs/loader:1117:32)\n' +
    '    at Module._load (node:internal/modules/cjs/loader:958:12)\n' +
    '    at Module.require (node:internal/modules/cjs/loader:1141:19)',
  module: undefined,
  loc: undefined,
  hideStack: true,
  chunk: undefined,
  file: undefined,
  hook: 'Compilation.hooks.processAssets',
  error: Error: Cannot find module 'typia/lib/programmers/AssertStringifyProgrammer'
  Require stack:
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/TypedRouteTransformer.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/MethodTransformer.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/NodeTransformer.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/FileTransformer.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transform.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typia@5.0.0_typescript@5.2.2/node_modules/typia/lib/transform.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/utils/typescript/load-ts-transformers.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/index.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/utils/with-nx.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/lib/get-webpack-config.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/config/schema-utils.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/executor-utils.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/run.js
  - /Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/bin/run-executor.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
      at Module._load (node:internal/modules/cjs/loader:920:27)
      at Module.require (node:internal/modules/cjs/loader:1141:19)
      at require (node:internal/modules/cjs/helpers:110:18)
      at Object.<anonymous> (/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js:19:35)
      at Module._compile (node:internal/modules/cjs/loader:1254:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
      at Module.load (node:internal/modules/cjs/loader:1117:32)
      at Module._load (node:internal/modules/cjs/loader:958:12)
      at Module.require (node:internal/modules/cjs/loader:1141:19) {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/programmers/TypedRouteProgrammer.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/TypedRouteTransformer.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/MethodTransformer.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/NodeTransformer.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transformers/FileTransformer.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nestia+core@1.6.7_@nestia+fetcher@1.6.7_@nestjs+common@10.2.2_@nestjs+core@10.2.2_@nestjs+pl_pe7vdozlf5sl32mqbygafecs6m/node_modules/@nestia/core/lib/transform.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typescript@5.2.2/node_modules/typescript/lib/typescript.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/typia@5.0.0_typescript@5.2.2/node_modules/typia/lib/transform.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/utils/typescript/load-ts-transformers.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+js@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/js/src/index.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/utils/with-nx.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/lib/get-webpack-config.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/@nx+webpack@16.7.4_@types+node@20.5.7_nx@16.7.4_typescript@5.2.2/node_modules/@nx/webpack/src/executors/webpack/webpack.impl.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/config/schema-utils.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/executor-utils.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/src/command-line/run/run.js',
      '/Users/oo00spy00oo/Sync/Projects/UniLab/dogetrixchain-nest-mono/node_modules/.pnpm/nx@16.7.4/node_modules/nx/bin/run-executor.js'
    ]
  }
}

Node.js v18.16.0

```

**Comment by samchon** [comment]
Rollback `typia` version. `nestia` will support `typia@5` at next v2 update.

**Comment by oo00spy00oo** [comment]
> 

Thanks for your reply!

**Comment by samchon** [comment]
Nestia v2 be released
